language: python

python:
- "3.6"

env:
- DJANGO=2.1

install:
- pip install -r requirements.txt

script:
- python manage.py test
- coverage run --source='.' manage.py test

after_success:
  - bash < (curl -s https://codecov.io/bash)
#- coverage run --source=habitica_slack manage.py test # create test coverage report

#after_script:
#- codeclimate-test-reporter --file .coverage # send test coverage report to code climate